### ISSUE TITLE
Remove footer from landing page

### ISSUE THREAD

**Issue by arka-nitd** [arka-nitd/digitalfortress#1]
As of now the footer in the landing page is of no use as the links are not set appropriately. Remove the footer from the landing page layout

**Comment by vsnehil92** [comment]
i can help in this

**Comment by makoru-hikage** [comment]
Only remove, not place?

**Comment by makoru-hikage** [comment]
In a jiffy.

**Comment by vsnehil92** [comment]
i could remove the footer anything else?
