### ISSUE TITLE
Add Email Verification Feature

### ISSUE THREAD

**Issue by arka-nitd** [arka-nitd/digitalfortress#3]
In the file HomeController.php the code for the email verification is not added yet. Instructions for the same is commented in the file in the function login. The feature which needs to be developed is email verification system, so that an user can signup using email and password. Unless he/she is verified when logged it, instead of dashboard verify email page should appear. On verification the user must be marked verified and moved to the verified users table ( currently named users )

**Comment by hydeenoble** [comment]
I would like to work on this, can I give it a try?

**Comment by arka-nitd** [comment]
@hydeenoble Yeah sure, go ahead :D

**Comment by hydeenoble** [comment]
Ok... great.

Hoping to have a PR as soon as possible

**Comment by hydeenoble** [comment]
Although your above explanation is not 100% clear.

**Comment by hydeenoble** [comment]
If I understand you clearly, A verification code is supposed to be sent to the user's email every time the user tries to login. right?

**Comment by arka-nitd** [comment]
@hydeenoble Not Everytime you need to sent verification email. Just like normal email authentication system in every other site, whenever the user registers he will get a authorization link emailed to him. On clicking that link in his email he will get a message that he is verified user now. So he should be able to login now. 
Some cases to consider :
1. If he is unverified he must not be allowed to login. 
2. There should be a link below login -  regenerate email authorization link.
3. If one tries to register with the same email address that belongs to an unverified user, he should be shown an appropriate message instead of email is taken.

You can do it in parts or altogether in a pull request. Its up to you. Thank you :D

**Comment by hydeenoble** [comment]
This makes a lot of sense, but is it contrary to what you commented in the code. I will make necessary adjustments and send in a PR as soon as possible.

**Comment by arka-nitd** [comment]
@hydeenoble Apologies for the confusion. Actually I had two ideas in mind. The first one was send a code to the email address and type it in the actual website. The second one was send an authorization link to the email address, opening which the user gets verified. You can do it according to your idea. Awaiting your PR :D
